# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  tab-app:
    image: tab
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tab-postgresql:5432/TAB
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://tab-postgresql:5432/TAB
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8080:8080
  tab-postgresql:

    image: postgres:14.2

    container_name: tab-database

    environment:
      - POSTGRES_DB=TAB_db
      - POSTGRES_USER=TAB
      - POSTGRES_PASSWORD=tab
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql/data/db-files

    volumes:
      - type: bind
        target: /var/lib/postgresql/data
        source: '$PWD/database'

    ports:
      - 5432:5432
